-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: meeting_state

-- DROP TYPE IF EXISTS public.meeting_state;

CREATE TYPE public.meeting_state AS ENUM
    ('NEW', 'ACTIVE', 'CONCLUDED');

ALTER TYPE public.meeting_state
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.meetings
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    team_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    state meeting_state NOT NULL DEFAULT 'NEW'::meeting_state,
    CONSTRAINT meetings_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

COMMENT ON COLUMN public.meetings.team_id
    IS 'The related team id of the meeting.';
ALTER TABLE IF EXISTS public.meetings
    ADD CONSTRAINT meetings_team_id_fkey FOREIGN KEY (team_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.meetings
    OWNER to postgres;

GRANT ALL ON TABLE public.meetings TO anon;

GRANT ALL ON TABLE public.meetings TO authenticated;

GRANT ALL ON TABLE public.meetings TO postgres;

GRANT ALL ON TABLE public.meetings TO service_role;

COMMENT ON TABLE public.meetings
    IS 'Stores all the Agity meetings.';

COMMENT ON COLUMN public.meetings.state
    IS 'The state of a specific meeting.';

